=head1 NAME

mod_perl Articles in Printed and Online media

=head1 DESCRIPTION

There are many mod_perl articles published on the web and printed
media. This document tries to partially cover these resources.

If you know of any other resources not listed on this page please let
us know at the L<users|maillist::list-users> mailing list.

=head1 Printed Media

  META: to be completed

=head1 Online Zines

=over

=item *

articles at take23.org: http://take23.org/articles/

=item *

mod_perl series at ApacheToday
http://apachetoday.com/search.php3?author=Stas:Bekman

=item *

mod_perl series at ApacheWeek http://www.apacheweek.com/

=item *

mod_perl articles at Perl.com
http://www.perl.com/pub/q/Article_Archive#mod_perl (better use search
and you will find other mod_perl articles which weren't catalogued
under mod_perl category)

=item *

Basic knowledge about Apache stages and mod_perl handlers article in
German. http://www.heise.de/ix/artikel/2000/01/156/


=item *



=item *



=item *





=back


  META: to be completed

=head1 Are You Interested in Publishing Your Own mod_perl Article?

  META: to be completed

=cut
