=head1 NAME

Changes

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time.

The most recent changes are listed first.

=head1 Ongoing

* add http://cpan.org and http://search.cpan.org/ [Stas]

* add theperlreview.com [Stas]

* add permonks.org [Stas]

* replace a link to perl FAQ with a link to www.perldoc.com [Stas]

* added "Further reading" [Thomas Klausner]

* articles : Search Google for I<mod_perl article> and added
  everything I could find: many TPJ articles (all I think) and a
  number of other web-based articles. [Per Einar Ellefsen]

* books:

  o Add "MySQL and Perl for the Web", 1 chapter about mod_perl

  o Add the Mason book [Per Einar]

  o Add "Running Weblogs with Slash" [Per Einar]

  o Re-arrange content again to add a section "technologies running
    under mod_perl" [Per Einar]



=head1 Fri 19 Apr 01:18:30 CET 2002

* Added references to a number of talks in a new section (which should
  preferably be moved to a conference part later on as mentioned in
  TODO) and some other articles. [Per Einar Ellefsen E<lt>per.einar
  (at) skynet.beE<gt>]

=cut
