=head1 NAME

Frequent mod_perl problems

=head1 Description

Some problems come up very often on the mailing list.  If there is
some important problem that is being reported frequently on the list
which is not included below, even if it is found elsewhere in the Guide,
please L<tell me|guide::help/Contacting_me>.

=head1 my() scoped variable in nested subroutines

See the section "L<my() Scoped Variable in Nested 
Subroutines|general::perl_reference/my___Scoped_Variable_in_Nested_Subroutines>".

=head1 Segfaults caused by PerlFreshRestart

See the section L<Evil things might happen when using
PerlFreshRestart|guide::troubleshooting/Evil_things_might_happen_when_using_PerlFreshRestart>

=head1 Maintainers

Maintainer is the person(s) you should contact with updates,
corrections and patches.

=over

=item *

Stas Bekman E<lt>stas (at) stason.orgE<gt>

=back


=head1 Authors

=over

=item *

Stas Bekman E<lt>stas (at) stason.orgE<gt>

=back

Only the major authors are listed above. For contributors see the
Changes file.


=cut

