=head1 NAME

Contribute at the Mailing List

=head1 Description

The first way to contribute to the mod_perl community is by following
the mailing list and helping out anyone else having problems.

=head1 Answering Questions

Since mod_perl is an open source technology, its main support facility
is the L<mailing lists|maillist::index>. Therefore it's very essential
to support users and developers by sharing your mod_perl and related
knowledge through answering questions and submitting interesting posts
that enrich the community's knowledge in the related topics.

You don't have to be a guru to be a very valuable person to the
mod_perl community. Through answering questions you learn a lot by
yourself and eventually become a guru yourself.

=head1 Helping Navigating the Documentation

mod_perl is one of the few open source projects that is bundled with a
lot of comprehensive documentation. And although the documentation is
well indexed, it can be hard to find the right piece of information,
especially for a novice mod_perl user. If you point someone to the
existing documentation, please try to point her to the specific URL
containing the information, and not just to "the mod_perl guide" in
general.

=cut

