=head1 NAME

Changes

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time.

The most recent changes are listed first.

=head1 ...

* browserbugs::browserbugs: Added discussion of length of error
  responses and how it's handled by IE, in relation to this
  discussion:
  http://mathforum.org/epigone/modperl/praibryrghin [Per Einar]

=head1 Wed May 29 12:41:24 SGT 2002

* Added mod_perl_tricks::mod_perl_tricks by Lincoln Stein. Changed it
  to meet our POD style, and some references to the CPAN. [Per Einar]

* Added scale_etoys::etoys tutorial by Perrin Harkins. [Per Einar]

* browserbugs::browserbugs moved here

* started the Tutorials docset [Thomas Klausner]

=head1 Sat Sep 15 19:45:41 SGT 2001

* templates::choosing, the initial version added (Perrin Harkins
  E<lt>perrin@elem.comE<gt>)

=cut
