=head1 NAME

Apache::httpd_conf - Generate an httpd.conf file

=head1 Synopsis

  use Apache::httpd_conf ();
  
  Apache::httpd_conf->write(Port => 8888);

=head1 Description

The Apache::httpd_conf module will generate a tiny httpd.conf file,
which pulls itself back in via a C<E<lt>PerlE<gt>> section. 

Any additional arguments passed to the C<write> method will be added
to the generated httpd.conf file, and will override those defaults set
in the C<E<lt>PerlE<gt>> section.  This module is handy mostly for
starting httpd servers to test mod_perl scripts and modules.

=head1 Author

Doug MacEachern

=head1 See Also

mod_perl, L<Apache::PerlSections>

=cut