=head1 NAME

Apache::Leak - Module for tracking memory leaks in mod_perl code

=head1 Synopsis

  use Apache::Leak;
  
  leak_test {
      my $obj = Foo->new;
      $obj->thingy;
  };
  #now look in error_log for results

=head1 Description

C<Apache::Leak> is a module built to track memory leaks in mod_perl
code.

=head1 See Also

C<Devel::Leak>

=head1 Author

Doug MacEachern

Leak.xs was derived from Nick Ing-Simmons' Devel::Leak

=cut
