=head1 NAME

Apache::Log - Interface to Apache logging

=head1 Synopsis

  use Apache::Log ();
  my $rlog = $r->log;
  $rlog->debug("You only see this if `LogLevel' is set to `debug'");
  
  my $slog = $r->server->log;

=head1 Description

The C<Apache::Log> module provides an interface to Apache's
I<ap_log_error> and I<ap_log_rerror> routines.

The methods listed below can be called as
C<$rE<gt>>I<meth>C<($error)>, and the error message will appear in the
error log depending on the value of C<LogLevel>.

=over 4

=item emerg

=item alert

=item crit

=item error

=item warn

=item notice

=item info

=item debug

=back

=head1 Maintainers

Maintainer is the person(s) you should contact with updates,
corrections and patches.

=over

=item * The L<documentation mailing list|maillist::docs-dev>

=back

=head1 Authors

=over

=item * Doug MacEachern

=back

Only the major authors are listed above. For contributors see the
Changes file.

=head1 See Also

mod_perl, L<Apache>.

=cut
