=head1 NAME

Changes

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time.

The most recent changes are listed first.

=head1 ???

* cvs_howto:

  o Changed incorrect repository names. Added some more references for
    some of them (mod_perl 2 and mod_perl docs) relative to their
    installation. Added a note about ViewCVS. [Per Einar]

  o Added section about CVS+SSH developer access. [Per Einar]

* perf_reference:

  o added a section on overriding functions to trace their failure.

  o inlined Mike Guy's news article about closures

  o use the caller() trick instead of $^S to figure out whether we are
    inside the eval() block. [Michael G. Schwern]

* correct headers.pod

  o rewrite the headers of this chapter [Per Einar Ellefsen]

  o Some minor syntactic changes (moved SYNOPSIS to description ...)
    [Per Einar]

* multiuser.pod

  o chroot(1) info

  o jail(8) info (Andrew McNaughton)

* started the general documents docset [Thomas Klausner]

  o Made several groups within this docset to preserve clarity. [Per
    Einar]

=cut
