=head1 NAME

CVS HowTo

=head1 Description

A short description how to use CVS to access the mod_perl and related
projects source distributions.

Just as cvs access to the Apache development tree, the mod_perl code
pulled from cvs is not guaranteed to do anything, especially not
compile or work.  But, that's exactly why we are using cvs, so
everyone has access the latest version and can help see to it that
mod_perl does compile and work on all platforms, with the various
versions and configurations of Perl and Apache.  Patches are always
welcome, simply testing the latest snapshots is just as, if not more
helpful.

It's recommended to subscribe to the L<modperl-cvs|maillist::cvs>
list, which is the place cvs commit logs and diffs are mailed to; at
least if you're going to work on the code.

=head1 anoncvs

You can get cvs here: http://www.cvshome.org/

=head2 checkout

To checkout a fresh copy run the following commands from the directory
you want the sources to stay in:

  % cvs -d ":pserver:anoncvs@cvs.apache.org:/home/cvspublic" login

(use the password "anoncvs")

  % cvs -d ":pserver:anoncvs@cvs.apache.org:/home/cvspublic" co modperl

After cvs finished downloading the files you will find a new directory
called I<modperl> in the current working directory.

=head2 keeping your copy up to date

To keep your local copy in sync with the repository, do

  % cvs -dP update

in the top directory of the project. You should run update evertime
before you start working on the project.

=head2 sending patches

To send a patch, first run:

  % cvs diff -u

in the top directory of the project. The output of diff will be sent
to STDOUT, so it might be better to redirect the output to a file:

  % cvs diff -u > patch

If you added files or directories to the project, do a diff against
I</dev/null>:

  % diff -u /dev/null newdir/newfilename

When this patch is applied, the new dir and the new file will be
automatically created.

On Windows-based systems, you can do

  % diff -u NUL newdir/newfilename

instead.

Then send your patch to the maintainer of the project.

=head2 usefull default parameters

Here are some recommended parameters. Save them in I<~/.cvsrc>, so
you don't have to type them everytime you use cvs.

  cvs -z9
  update -dP
  diff -u

I<cvs -z9> sets the compression level to 9 (the highest value) to
speed up downloading.

I<update -d> automatically creates directories that are missing in
your local copy because they where added to the repository after your
initial checkout or your last update.

I<update -P> automatically deletes empty directories.

I<diff -U> to use the unified output format so that your changes can
be easily merged back into the repository.

=head1 cvsup

Cvsup has come out of the FreeBSD group. It's a client/server beast
that offers an efficient way to sync collections of files over the
net, and it is very CVS aware, allowing synchronisation of
repositories or checked out files using the cvs deltas to bring the
client side files up to date with minimal data transfer.

For a FreeBSD cvsup client see:

http://www.freebsd.org/cgi/ports.cgi?query=cvsup&stype=all

Others (SunOS, alpha.osf, linux, Solaris2.4, HPAA 10.2, irix)
ftp://ftp.postgresql.org/pub/CVSup/

Here's a config file for the client (cvsup) to sync modperl sources.

  *default tag=.
  # comment out the above if you want the raw cvs files
 
  *default host=cvs.apache.org
  *default prefix=/path/on/this/machine/to/install/
  # a subdir for modperl will appear here ^^^
 
  *default base=/path/on/this/machine/where/cvsup/will/keep/status/info
  # you'll never need to look in the 'base' dir.
 
  *default release=cvs delete use-rel-suffix compress
 
  modperl
  #apache-src
  #apache-docs
  #uncomment these two for the latest apache src and/or docs if you want them

=head1 mod_perl and related projects on cvs.apache.org

=over

=item modperl

sources for mod_perl 1.x, for use with apache-1.3

=item apache-1.3

the Apache 1.3 HTTP Server

=item mod_perl-2.0

the new version of mod_perl, for use with httpd-2.0

=item httpd-2.0

the new Apache 2.0 HTTP Server

=item apr

needed for mod_perl-2.0

=item apr-util

needed for mod_perl-2.0

=item mod_perl-docs

the mod_perl documentation (i.e. this site)

=back

Or see http://cvs.apache.org/viewcvs.cgi/ for a list of all projects.

=head1 See also

=over

=item * http://httpd.apache.org/dev/anoncvs.txt

For a basic introduction to anoncvs

=item * http://cvsbook.red-bean.com/

Open Source Development with CVS is a book published by Coriolis Inc.
as part of the Coriolis OpenPress series. Chapters 2, 4, 6, 8, 9, and
10 -- comprising a complete introduction, tutorial and reference to
CVS -- are being released free under the terms of the GNU General
Public License.

=item * http://www.cvshome.org/docs/manual/

Version Management with CVS by Per Cederqvist et al is the "official"
manual for CVS.  Commonly known as "the Cederqvist," the manual covers
repositories, branches, and file maintenance, and includes reference
material for both CVS users and CVS repository administrators.

=back

=head1 Maintainers

Maintainer is the person(s) you should contact with updates,
corrections and patches.

=over

=item *

the L<documentation mailing list|maillist::docs-dev>

=back


=head1 Authors

=over

=item *

Thomas Klausner E<lt>domm (at) zsi.atE<gt>

=item *

Doug MacEachern

=back

Only the major authors are listed above. For contributors see the
Changes file.

=cut
