=head1 NAME

Binary mod_perl distributions

=head1 Description

This document includes links to various binary mod_perl distributions.

If you know about a distribution that isn't listed here, please tell
us (by announcing it at the L<mod_perl list|maillist::modperl>).

See also L<the source distributions|download::source> and the
L<bundles|download::bundles>.

=head1 How to get pre-compiled mod_perl 1.0

=head2 Win32 build

Please see the section on L<Win32 mod_perl 1.0 binary
distributions|docs::1.0::os::win32::install/All_in_one_packages>
for details on getting all-in-one mod_perl 1.0 binary packages. 

=head2 Win32 Active Perl

See the section on L<Win32 mod_perl 1.0 ppm
packages|docs::1.0::os::win32::install/PPM_Packages>
for details on obtaining mod_perl 1.0 via ActivePerl's C<ppm>
utility, and L<Win32 mod_perl 2.0 ppm
packages|docs::2.0::os::win32::install/PPM_Packages>
for the corresponding discussion for mod_perl 2.0 packages.

=head2 RedHat Linux

Static mod_perl and libapreq (Apache::Request) RPMs and SRPMs (made by
David Harris ) http://www.davideous.com/modperlrpm/distrib/. Mirrored at
http://perl.apache.org/rpm/.

=head2 RedHat Linux (including php3)

i386 RPMs + SRPM (RedHat) of Apache with mod_perl and php3 built
staticaly. (made by Vladimir Ivaschenko)
http://www.hazard.maks.net/apache/

=head2 other OS

OS vendors may supply their own pre-compiled version of mod_perl.
Refer to your OS vendor to figure out if they provide a binary version
of mod_perl.

=head1 How to get pre-compiled mod_perl 2.0

=head2 Win32

Please see the section on L<Win32 mod_perl 2.0 binary
distributions|docs::2.0::os::win32::install/All_in_one_packages>
for details on getting all-in-one mod_perl 2.0 binary packages. 

=head2 Fedora

http://buscaluz.org/rpms/ (by Stuart Jansen)



=cut
