=head1 NAME

Documentation

=head1 Description

You may want to download and install the mod_perl documentation
locally for easier reading, or to submit documentation patches.

To install the documentation you will have to install the whole site
at the same time though, but this should just be a benefit because you
can mirror the whole site locally and have access to all the
information available here.

=head1 Download

The mod_perl documentation lives in the C<cvs.apache.org> CVS
server. To get it, you will need to checkout a copy. Assuming you have
CVS installed, run the following commands from the directory you want
to place the I<modperl-docs> directory in:

  % cvs -d:pserver:anoncvs@cvs.apache.org:/home/cvspublic login
    (use the password "anoncvs")
  % cvs -d:pserver:anoncvs@cvs.apache.org:/home/cvspublic co modperl-docs

You will now find a directory called I<modperl-docs> in the current
working directory which contains all the sources needed to build the
site. See the L<CVS Howto|contribute::cvs_howto> for more information.

Another way to download the sources, if you don't want to use CVS, is
to get the snapshots available from
http://cvs.apache.org/snapshots/modperl-docs/ . However, it will be a
major drag for you to keep these up to date, so you are better advised
to use the CVS access.

=head1 Build

The build process is very simple, as we have developed a number of
tools which are very helpful in this task. However, you will need a
number of prerequisites before starting.

=head2 Prerequisites

DocSet: while it is included with the CVS distribution, please
download it from CPAN and install the latest version. It will install
the tool C<html2ps>, which is needed to build the PDF version, and
also a number of Perl modules (it will tell you the Perl modules
prerequisites).

For the PDF version, you will also need a command-line tool called
C<ps2pdf>, which is included with the Ghostscript distribution: see
http://www.ghostscript.com/ . You will probably also need the
I<netpbm> package.

 META: we need specifics about netpbm

=head2 Normal build process

The programs used to build the site are included in the directory you
checked out from CVS. To build the whole site, run this while being
placed in the I<modperl-docs> directory.

  % bin/build

This will place the site in the sub-directory I<dst_html>. You may
open I<index.html> in there to start browsing the site.

If you are using the Windows operating system, please see the file
I<INSTALL.win32> for some win32-specific information.

=head2 PDF version

Now, you can go back to your I<modperl-docs> directory. Building the
PDF version is as easy as with the HTML version, just do a simple:

  % bin/build -d

And the PDF version will be built. This is often very time-consuming
and heave on resources though. The results will be placed in
I<dst_html> too, with links on the HTML pages to the PDF versions. A
I<dst_ps> directory is also created, which contains intermediate HTML,
PostScript and PDF files.

=head1 Keeping your local copy up to date

Now that you have a working copy of the mod_perl site, you will want
to keep your documentation up to date. It is updated quite frequently,
so you might want to follow the L<docs-cvs mailing
list|maillist::docs-cvs> to see when changes are made.

Once you see a change is made, you need to update your CVS working
copy, and re-build the site (although it will only rebuilt modified
files).

  % cvs up
  % bin/build

Rebuilding the PDF version is just as easy, just run:

  ai% bin/build -d

There are some times however when a simple rebuild will not be enough:
usually when there are changes made to the design or to I<config.cfg>
files. In that case, you will need to force the whole rebuild:

  % bin/build -f
  % bin/build -df    # if you want PDF to be rebuilt.

=head1 Submitting documentation patches

We warmly welcome any updates to the documentation. To send us a
documentation patch, please update your CVS tree, and then, depending
on the patch:

=over

=item *

If the change is big, send the whole source file to the maintainer.

=item *

If you only add a paragraph/modify a line, please make sure you have
the I<latest> CVS version, and then issue:

  % cvs diff -u > patch

And send the I<patch> file to the maintainer, preferably inline in
your e-mail.

=back

When writing documentation, please make sure to read the files
contained in I<admin/> in the CVS tree, especially I<style.pod>, to
see what guidelines you should follow.

=head1 Maintainers

Maintainer is the person(s) you should contact with updates,
corrections and patches.

=over

=item *

the L<documentation mailing list|maillist::docs-dev>

=back


=head1 Authors

=over

=item *

Per Einar Ellefsen E<lt>per.einar (at) skynet.beE<gt>

=back

Only the major authors are listed above. For contributors see the
Changes file.

=cut

