=head1 NAME

Source mod_perl distributions

=head1 Description

This document explains how to get the mod_perl 1.0 and 2.0 source
distributions.

See also L<the binary distributions|download::binaries> and the
L<bundles|download::bundles>.

There is also L<information on 3rd party
modules|download::third_party>.


=head1 mod_perl 2.0

Be sure to read the I<README> and I<INSTALL> documents (in the
distribution package) and the longer mod_perl 2.0 L<installation
guide|docs::2.0::user::install::install>.

=head2 Stable mod_perl 2.0 Source Distribution

=over

=item * Master Source distribution

Release http://apache.org/dist/perl/

=item * CPAN

Currently the released versions include C<_> in them (e.g.,
mod_perl-2.0.2.tar.gz), so they are invisible via C<CPAN.pm> or
http://search.cpan.org/. But they are available from CPAN dir:

http://search.cpan.org/dist/mod_perl/

=back

=head2 Development mod_perl 2.0 Source Distribution

=over

=item * The latest SVN snapshot

http://svn.apache.org/snapshots/modperl-2.0/

=item * SVN Access

To download the svn version of mod_perl-2.0 execute the following
commands:

  % svn checkout https://svn.apache.org/repos/asf/perl/modperl/trunk/ mod_perl-2.0

Developers: In order to commit for the first time you will need to
update your password.  To do that, visit:  

https://svn.apache.org/change-password



=item * Apache/APR SVN

To download the svn version of httpd-2.0 and bring it to the same
state of the distribution package, execute the following commands:

(Use http:// instead of https:// if you don't plan to commit changes)

For httpd 2.0 (the stable Apache 2.0 branch):

  % svn checkout https://svn.apache.org/repos/asf/httpd/httpd/branches/2.0.x/ httpd-2.0
  % cd httpd-2.0/srclib
  % svn checkout https://svn.apache.org/repos/asf/apr/apr/branches/0.9.x/ apr
  % svn checkout https://svn.apache.org/repos/asf/apr/apr-util/branches/0.9.x/ apr-util
  % cd ..
  % ./buildconf

Once extracted, whenever you want to sync with the latest httpd-2.0
version and rebuild, run:

  % cd httpd-2.0
  % svn update
  % make distclean && ./buildconf

For httpd 2.1 (the development Apache 2.0 branch) use this instead:

  % svn checkout https://svn.apache.org/repos/asf/httpd/httpd/trunk/ httpd-2.1
  % cd httpd-2.1/srclib
  % svn checkout https://svn.apache.org/repos/asf/apr/apr/trunk/ apr
  % svn checkout https://svn.apache.org/repos/asf/apr/apr-util/trunk/ apr-util









=item * RPMs

Some RPM packages for the bleeding mod_perl versions can be searched
for using rpmfind services, e.g.:

http://www.rpmfind.net/linux/rpm2html/search.php?query=mod_perl&submit=Search+...

=back

=head2 mod_perl 2.0 SVN Web Interface

http://svn.apache.org/viewvc/perl/modperl/trunk/

=cut



=head1 mod_perl 1.0

Be sure to read the I<README> and I<INSTALL> documents (in the
distribution package) and the longer L<the installation
guide|docs::1.0::guide::install>.

=head2 Stable mod_perl 1.0 Source Distribution

=over

=item * Master Source distribution

Release http://apache.org/dist/perl/

=item * CPAN

http://www.cpan.org/modules/by-module/Apache/

=back

=head2 Development mod_perl 1.0 Source Distribution

=over

=item * The latest SVN snapshot

http://svn.apache.org/snapshots/modperl/

=item * SVN Access

To download the svn version of mod_perl-1.0 execute the following
commands:

  % svn checkout https://svn.apache.org/repos/asf/perl/modperl/branches/1.x/ modperl-1.0

Developers: In order to commit for the first time you will need to
update your password. To do that visit:

https://svn.apache.org/change-password

=back

=head2 mod_perl 1.0 SVN Web Interface

http://svn.apache.org/viewvc/perl/modperl/branches/1.x/
