=head1 NAME

Changes

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time.

The most recent changes are listed first.

=head1 17 Apr 2002  

* Changed Introduction to Description, and ** to B tags in POD.  [Per
  Einar Ellefsen]

=head1 21 Oct 2001  

* Minor corrections, converted to .POD format [Ged]

=head1 18 Dec 2000  

* Minor corrections and additions [Ged]

=head1 11 Jun 2000

* Initial publication for comment [Ged Haywood]

=cut
