=head1 NAME

Test Development mailing list

=head1 Description

The B<test-dev> mailing list is for discussing I<Apache HTTP Test>
L<http://httpd.apache.org/test/> project. It's linked from here,
because mod_perl's sub-project C<Apache::Test> is discussed on this
list.

Please read the mailing list L<Guidelines|email-etiquette> before
posting.

=head1 Subscription Information

To subscribe or unsubscribe send an empty email to one of the
following addresses.

=over

=item * subscribe to the list

mailto:test-dev-subscribe@httpd.apache.org

=item * subscribe to the list's digest

mailto:test-dev-subscribe-digest@httpd.apache.org

=item * unsubscribe from the list

mailto:test-dev-unsubscribe@httpd.apache.org

=item * get help with the list

mailto:test-dev-help@httpd.apache.org

=back

=head1 Searchable Archives

=over

=item * www.apachelabs.org

http://www.apachelabs.org/test-dev/ 

=item * Mbox file

http://httpd.apache.org/mail/test-dev/ 

=back


=cut

