=head1 NAME

CHANGES

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time.

The most recent changes are listed first.

=head1 Thu Apr 18 09:10:00 CET 2002

Per Einar Ellefsen E<lt>per.einar (at) skynet.beE<gt>

* Re-arranged the order of the FAQs.

* Changed titles of documents to not include underscores, and of
  headings inside documents to not be upper-case.

* Corrected links and removed stale ones.

* Fixed authors where needed.

* Did some slight content review, added C<CE<lt>E<gt>>, C<BE<lt>E<gt>>
  ...  on many places to make it more readable.

=head1 Sat Sep 15 19:45:41 SGT 2001

* docs ported from the old site

* faqs::mod_perl_trap

These contributors to the ported to the new site version were:

  Jens Heunemann E<lt>heunemann2@janet.deE<gt>,
  David Landgren E<lt>david@landgren.netE<gt>,
  Mark Mills E<lt>mark@ntr.netE<gt> and 
  Randal Schwartz E<lt>merlyn@stonehenge.comE<gt>

Now maintained by the modperl community

=cut
