=head1 NAME

CHANGES

=head1 Description

Refer to this document to learn what changes were made to the
documents, since you've read these last time.

The most recent changes are listed first.

=head1 Sat Sep 15 19:45:41 SGT 2001

* docs ported from the old site

* faqs::mod_perl_trap

These contributors to the ported to the new site version were:

  Jens Heunemann E<lt>heunemann2@janet.deE<gt>,
  David Landgren E<lt>david@landgren.netE<gt>,
  Mark Mills E<lt>mark@ntr.netE<gt> and 
  Randal Schwartz E<lt>merlyn@stonehenge.comE<gt>

Now maintained by the modperl community

=cut
