=head1 NAME

ModPerl::RegistryNG - Run unaltered CGI scripts persistently under mod_perl

=head1 Synopsis

=head1 Description

This modules is just a back compatibility alias. Use
C<L<ModPerl::Registry>> instead.

=head1 Authors

Doug MacEachern

Stas Bekman

=head1 See Also

C<L<ModPerl::RegistryCooker>>, C<L<ModPerl::Registry>>, Apache(3),
mod_perl(3)

=cut
